FROM node:alpine AS developement

WORKDIR /usr/src/app

COPY package.json ./
COPY pnpm-lock.yaml ./
COPY tsconfig.json tsconfig.json

RUN npm i -g pnpm
RUN pnpm i

COPY apps/notifications apps/notifications
COPY libs libs

RUN cd apps/notifications && pnpm i


RUN pnpm run build

FROM node:alpine AS production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY package.json ./
COPY pnpm-lock.yaml ./

RUN npm i -g pnpm
RUN pnpm i --prod

COPY --from=development /usr/src/app/dist ./dist

CMD ["node", "./dist/apps/notifications/main"]



